<?php
/**
 * This is used to send a testmail to the user specified in the "recipient" parameter
 * 
 * 
 */
$t_plugin_path = config_get( 'plugin_path' );
require_once( $t_plugin_path . 'Smime' . DIRECTORY_SEPARATOR . 'Smime.php' );

html_page_top(lang_get( 'plugin_smime_title'  ) );

$user = gpc_get_int('recipient');


$mail = new SmimePHPMailer();
$from_email = config_get("from_email");
$from_name = config_get("from_name");
$smtp_user = config_get("smtp_username");
$smtp_pass = config_get("smtp_password");
$smtp_host = config_get("smtp_host");
$recipient_email = user_get_email($user);
$pubkey = SmimePlugin::loadPubkey($user);

$body = "This is a test mail generated by the Mantis S/MIME Plugin. הצü";
$subject = "Mantis S/MIME Testmail - הצü";
$headers = array("From" => $from_email, "To" => $recipient_email, "Subject" => $subject, "X-Mailer" => "PHP/".phpversion());




//instance of new Mailer
$mail = new SmimePHPMailer();

$mail->IsSMTP();  // telling the class to use SMTP

$mail->Host     = $smtp_host; // SMTP server
$mail->SMTPAuth = true;
$mail->Username     = $smtp_user;
$mail->Password     = $smtp_pass;

$mail->FromName     = $from_name;
$mail->From     = $from_email;
$mail->email_address = $recipient_email;
$mail->AddAddress($recipient_email,user_get_name($user));

$mail->Subject  = $subject;
$mail->Body     = $body;
$mail->WordWrap = 50;
$mail->Encoding = 'base64';
$mail->CharSet = 'utf-8'; 

//add publickey array for encryption
$mail->setEncrypt_key_files(array($pubkey));
if(!$mail->Send()) {
	error_log('Message was not sent.');
	error_log('Mailer error: ' . $smail->ErrorInfo);
	$success = false;
} else {
	error_log('Message has been sent.');
	$success = true;
}

echo "<pre>\n";
echo "Result:\n";
if($success)
{
	echo "<font color=\"#00ff00\">";
	echo plugin_lang_get("success");
	echo "</font>";
}
else
{
	echo "<font color=\"#ff0000\">";
	echo plugin_lang_get("error");
	echo "</font>";
}
echo "</pre>\n";




html_page_bottom();